### ISSUE TITLE
Day01 #2

### ISSUE THREAD

**Issue by cant0r** [jabbalaci/AdventOfCode2023#1]
-

**Comment by cant0r** [comment]
Oops, I think I meant to put just `line` instead of `line[::-1]` there.

**Comment by jabbalaci** [comment]
? I don't get it.

**Comment by cant0r** [comment]
I was on mobile when I first opened this issue but I noticed some errors in my question regarding your Part 2 solution so I tried to revert this issue. Unfortunately, I couldn't on mobile, or at least, I did not find a way.

I was to inquiry about dynamically producing the regex pattern, I had an idea on how to do it but I couldn't decide whether the code would remain "pythonic" or not:

```python
def process(line: str) -> int:
    m = re.search(rf"[0-9]|{'|'.join([d for d in DIGITS)}", line)
    assert m
    first = text2number(m.group())
    #
    m = re.search(rf"[0-9]|{'|'.join([d[::-1] for d in DIGITS])}", line[::-1])
    assert m
    last = text2number(m.group()[::-1])

    return first * 10 + last
```

**Comment by jabbalaci** [comment]
Here, I prefer the more explicit way that I find more readable. Thanks, anyway.
